### PR TITLE
Configure Git identity

### PR DESCRIPTION
**Pull request by krlmlr**
This seems necessary now on the macOS builds. Is this something that we should do here, or in the R code?

### CODE REVIEW

**Comment by pat-s** [comment]
I do not see a failing build which relates to a missing git identity. Can you provide more context?

**Comment by pat-s** [comment]
I still do not see a need for this. Do we really need this?

**Comment by krlmlr** [comment]
macOS builds needed this at some point.

**Comment by pat-s** [comment]
I haven't seen builds failing even though I watch them daily in the last month. Anyways, because this is a full new block, I would not add this unless we really need it?

**Pull request closed without merging**
