### PR TITLE
- DSL: Don't add steps twice, if present in a previous macro

### LINKED ISSUE #145: Don't add steps twice, if present in a previous macro
From https://github.com/ropenscilabs/tic/pull/142#issuecomment-482895488.

Applies if steps appear in multiple macros.

### PR DESCRIPTION
**Pull request by pat-s**
fixes #145 

Only applies to fully identical duplicates.

### CODE REVIEW

**Comment by pat-s** [comment]
ping @krlmlr

**Comment by pat-s** [comment]
ping @krlmlr

**Comment by krlmlr** [comment]
What happens if we add two steps with the same name but different arguments?

**Comment by pat-s** [comment]
@krlmlr seems to work fine. Updated the test.

**Pull request merged**
